apiVersion: v1
kind: Service
metadata:
  name: express-web-service
  labels:
    meanpug.com/app: express-web
spec:
  type: NodePort
  selector:
    app: express-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
